---
- name: Get OCP Release Version
  register: ocp_release_version
  ansible.builtin.shell: curl -s {{ hypershift.asc.url_for_ocp_release_file }}  | awk '/machine-os / { print $2 }'

- name: Create Config map mirror-config ( For updating AgentServiceConfig with the brew mirror information )
  ansible.builtin.template:
    src: mirror-config.yml.j2
    dest: /root/ansible_workdir/mirror-config.yaml

- name: Deploy Config map - mirror config
  ansible.builtin.shell: oc apply -f /root/ansible_workdir/mirror-config.yaml

- name: Create agenterviceconfig.yaml
  ansible.builtin.template:
    src: agent_service_config.yaml.j2
    dest: /root/ansible_workdir/agentserviceconfig.yaml

- name: Deploy AgentServiceConfig
  ansible.builtin.command: oc apply -f /root/ansible_workdir/agentserviceconfig.yaml

- name: Wait for Agent Service Deployment to be Succeeded
  register: asc
  until: asc.stdout == '0'
  retries: 60
  delay: 20
  ansible.builtin.shell: oc get AgentServiceConfig agent -o json | jq -r '.status|.conditions[]|.status' | grep False | wc -l

- name: Wait for MCE to be available
  register: mce_status
  until: mce_status.stdout == "Available"
  retries: 40
  delay: 10
  ansible.builtin.shell: oc get mce --no-headers | awk  '{print $2}'
