---
- name: Wait for All Cluster Operators to be available
  register: co
  until: co.stdout == '0'
  retries: 60
  delay: 20
  ansible.builtin.shell: oc get co --kubeconfig=/root/ansible_workdir/{{ hypershift.hcp.hosted_cluster_name }}-kubeconfig --no-headers| awk '$3 != "True" {print $1}'
    | wc -l

- name: Wait for Hosted Control Plane to Complete
  register: hc_status
  until: hc_status.stdout == "Completed"
  retries: 40
  delay: 15
  ansible.builtin.shell: oc get hc -n {{ hypershift.hcp.clusters_namespace }} --no-headers | awk  '{print $4}'

- name: Get URL for Webconsole of Hosted Cluster
  register: console_url
  ansible.builtin.shell: oc whoami --show-console --kubeconfig=/root/ansible_workdir/{{ hypershift.hcp.hosted_cluster_name }}-kubeconfig

- name: Get Password for Hosted Cluster
  register: cluster_password_encoded
  ansible.builtin.shell: oc get secret kubeadmin-password -n "{{ hypershift.hcp.clusters_namespace }}-{{ hypershift.hcp.hosted_cluster_name }}" -o yaml | grep -i
    'password:'

- name: Decode the Password
  register: cluster_password_decoded
  ansible.builtin.shell: echo "{{cluster_password_encoded.stdout_lines[0].split(' ')[-1]}}" | base64 --decode

- name: Get api server of Hosted Cluster
  register: api_server
  ansible.builtin.shell: "cat /root/ansible_workdir/{{ hypershift.hcp.hosted_cluster_name }}-kubeconfig | grep -i server:"

- name: Display Login Credentials
  ansible.builtin.debug:
    msg: " You can access webconsole of Hosted Cluster here : {{ console_url.stdout }} | Username : 'kubeadmin' Password : {{ cluster_password_decoded.stdout_lines[0]
      }} "

- name: Display oc login command for CLI
  ansible.builtin.debug:
    msg: " You can access the Hosted Cluster using CLI : oc login {{ api_server.stdout_lines[0].split(': ')[-1] }} -u kubeadmin -p {{ cluster_password_decoded.stdout_lines[0]
      }} "
