---
- name: Get the IPs of Hosted Cluster Workers
  register: hosted_workers
  ansible.builtin.shell: oc get no -o wide  --kubeconfig=/root/ansible_workdir/{{ hypershift.hcp.hosted_cluster_name }}-kubeconfig --no-headers|grep -i worker| awk
    '{print $6}'

- name: Configuring HAproxy for Hosted Cluster
  ansible.builtin.blockinfile:
    path: /etc/haproxy/haproxy.cfg
    block: |
      listen {{ hypershift.hcp.hosted_cluster_name }}-console
          mode tcp
          bind {{ hypershift.bastion_hypershift }}:443
          bind {{ hypershift.bastion_hypershift }}:80

- name: Add Hosted Cluster Worker IPs to Haproxy
  loop: "{{ range(hypershift.agents_parms.agents_count|int) | list }}"
  ansible.builtin.lineinfile:
    path: /etc/haproxy/haproxy.cfg
    line: "    server {{ hypershift.hcp.hosted_cluster_name }}-worker-{{item}} {{ hosted_workers.stdout_lines[item]}}"

- name: restart haproxy
  ansible.builtin.service:
    name: haproxy.service
    state: restarted
    enabled: true
