---
- name: Load in variables
  tags: ssh_copy_id, ssh
  ansible.builtin.include_vars: "{{ inventory_dir }}/group_vars/all.yaml"

- name: Delete SSH key from known hosts if it already exists for idempotency
  tags: ssh_copy_id, ssh
  ansible.builtin.lineinfile:
    path: ~/.ssh/known_hosts
    search_string: "{{ ssh_target[0] }}"
    state: absent

- name: Use template file to create expect script
  tags: ssh_copy_id, ssh
  delegate_to: 127.0.0.1
  ansible.builtin.template:
    src: ssh-copy-id.exp.j2
    dest: "{{ role_path }}/files/ssh-copy-id-expect-pass.exp"
    force: true

- name: Copy expect file to jumphost first, if not running on localhost.
  tags: ssh_copy_id, ssh
  when: inventory_hostname != '127.0.0.1'
  ansible.builtin.copy:
    src: "{{ role_path }}/files/ssh-copy-id-expect-pass.exp"
    dest: ~/.ssh/ssh-copy-id-expect-pass.exp

- name: Print results of copying ssh id to remote host
  tags: ssh_copy_id, ssh
  when: inventory_hostname != '127.0.0.1'
  ansible.builtin.debug:
    var: ssh_copy

- name: Copy SSH ID from controller to remote host with pre-provided password.
  tags: ssh_copy_id, ssh
  register: ssh_copy
  when: inventory_hostname == '127.0.0.1'
  ansible.builtin.command: expect {{ role_path }}/files/ssh-copy-id-expect-pass.exp

- name: Print results of copying ssh id to remote host
  tags: ssh_copy_id, ssh
  when: inventory_hostname == '127.0.0.1'
  ansible.builtin.debug:
    var: ssh_copy

- name: Copy SSH ID from jumphost to remote host with pre-provided password.
  tags: ssh_copy_id, ssh
  register: ssh_copy
  when: inventory_hostname != '127.0.0.1'
  ansible.builtin.command: expect ~/.ssh/ssh-copy-id-expect-pass.exp

- name: Print results of copying ssh id to remote host
  tags: ssh_copy_id, ssh
  when: inventory_hostname != '127.0.0.1'
  ansible.builtin.debug:
    var: ssh_copy

- name: Delete templated expect script on controller.
  tags: ssh_copy_id, ssh
  delegate_to: 127.0.0.1
  ansible.builtin.file:
    path: "{{ role_path }}/files/ssh-copy-id-expect-pass.exp"
    state: absent

- name: Delete templated expect script on jumphost.
  tags: ssh_copy_id, ssh
  when: inventory_hostname != '127.0.0.1'
  ansible.builtin.file:
    path: "{{ role_path }}/files/ssh-copy-id-expect-pass.exp"
    state: absent

- name: Ensure ssh-copy-id files folder exists for future runs.
  tags: ssh_copy_id, ssh
  delegate_to: 127.0.0.1
  ansible.builtin.file:
    path: "{{ role_path }}/files/"
    state: directory
