---
- name: Find inventory directory from ansible.cfg
  tags: set_inventory
  register: find_inventory
  ansible.builtin.shell: cat {{ ansible_config_file }} | grep 'inventory=' | cut -f2 -d"="

- name: Find absolute path to project.
  tags: set_inventory
  register: find_project
  ansible.builtin.shell:

- name: Fail if network_mode is NAT and jumphost vars are undefined.
  tags: set_inventory
  when: ( env.network_mode | upper == 'NAT' ) and (env.jumphost.name is none or env.jumphost.ip is none or env.jumphost.user is none or env.jumphost.pass is none
    or env.jumphost.path_to_keypair is none)
  ansible.builtin.fail:
    msg: "Error jumphost vars undefined: when env.network_mode is NAT, you must set all env.jumphost variables."

- name: Template out inventory with localhost, file server, KVM host, jumphost(optional) and bastion information
  tags: set_inventory
  ansible.builtin.template:
    src: hosts.j2
    dest: "{{ find_project.stdout }}{{ find_inventory.stdout }}/hosts"
    force: true

- name: Add path to Ansible private key in ansible.cfg
  tags: set_inventory
  ansible.builtin.lineinfile:
    line: private_key_file=~/.ssh/{{ env.ansible_key_name }}
    path: "{{ ansible_config_file }}"
    regexp: private_key_file
    state: present

- name: check inventory setup
  tags: set_inventory
  register: inv_check
  failed_when: inv_check.rc != 0
  ansible.builtin.command: ansible-inventory --list

- name: Gather facts to re-read inventory after changes made to inventory
  tags: set_inventory
  ansible.builtin.gather_facts:

- name: Refresh inventory
  tags: set_inventory
  ansible.builtin.meta: refresh_inventory
