---
- name: Find inventory directory from ansible.cfg
  tags: set_inventory
  register: find_inventory
  ansible.builtin.shell: cat {{ ansible_config_file }} | grep 'inventory=' | cut -f2 -d"="

- name: Find absolute path to project.
  tags: set_inventory
  register: find_project
  ansible.builtin.shell:

- name: Create inventory
  ansible.builtin.template:
    src: inventory_template.j2
    dest: "{{ find_project.stdout }}{{ find_inventory.stdout }}/inventory_hypershift"

- name: Check if SSH key exists
  register: ssh_key
  ansible.builtin.stat:
    path: ~/.ssh/{{ env.ansible_key_name }}.pub

- name: Generate SSH key
  when: ssh_key.stat.exists == false
  ansible.builtin.command: ssh-keygen -t rsa -b 4096 -N "" -f "~/.ssh/{{ env.ansible_key_name }}"

- name: Create expect file
  ansible.builtin.template:
    src: ssh-key.exp.j2
    dest: "{{ find_project.stdout }}{{ find_inventory.stdout }}/ssh-key.exp.sh"
    mode: +rx

- name: Add ssh-key to kvm_host Authorised Keys
  block:
    - name: Adding ssh key
      shell: "{{ find_project.stdout }}{{ find_inventory.stdout }}/ssh-key.exp.sh"
  rescue:
    - name: Key already added
      debug:
        msg: Ignore the above error if ssh-key already added
