---
- name: Change permissive domain for httpd
  tags: httpd
  community.general.selinux_permissive:
    name: httpd_t
    permissive: true

- name: Allow httpd to listen on tcp port 4443
  tags: httpd
  community.general.seport:
    ports: 4443
    proto: tcp
    setype: http_port_t
    state: present
    reload: true

- name: enable httpd
  tags: httpd
  ansible.builtin.systemd:
    name: httpd
    enabled: true

- name: restart httpd
  tags: httpd
  ansible.builtin.service:
    name: httpd
    state: restarted
