---
- name: Wait for agents to join the cluster
  register: agents
  until: agents.resources | length == {{ hypershift.agents_parms.agents_count }}
  retries: 30
  delay: 10
  kubernetes.core.k8s_info:
    api_version: agent-install.openshift.io/v1beta1
    kind: Agent

- name: Get agent names
  register: agents_info
  ansible.builtin.command: oc get agents -n {{ hypershift.hcp.clusters_namespace }}-{{ hypershift.hcp.hosted_cluster_name }} --no-headers

- name: Create List for agents
  ansible.builtin.set_fact:
    agents: []

- name: Get a List of agents
  loop: "{{ range(hypershift.agents_parms.agents_count|int) | list }}"
  ansible.builtin.set_fact:
    agents: "{{ agents + [agents_info.stdout.split('\n')[item].split(' ')[0]] }}"

- name: Patch Agents
  loop: "{{ range(hypershift.agents_parms.agents_count|int) | list }}"
  ansible.builtin.shell: oc -n {{ hypershift.hcp.clusters_namespace }}-{{ hypershift.hcp.hosted_cluster_name }}  patch agent {{ agents[item] }} -p '{"spec":{"installation_disk_id":"/dev/vda","approved":true,"hostname":"worker-{{item}}.{{
    hypershift.hcp.hosted_cluster_name }}.{{ hypershift.hcp.basedomain }}"}}' --type merge

- name: Scale Nodepool
  ansible.builtin.command: oc -n {{ hypershift.hcp.clusters_namespace }} scale nodepool {{ hypershift.hcp.hosted_cluster_name }} --replicas {{ hypershift.agents_parms.agents_count
    }}

- name: Wait for Agentmachines to create
  register: agent_machines
  until: agent_machines.resources | length == {{ hypershift.agents_parms.agents_count }}
  retries: 30
  delay: 10
  kubernetes.core.k8s_info:
    api_version: capi-provider.agent-install.openshift.io/v1alpha1
    kind: AgentMachine

- name: Wait for Machines to create
  register: machines
  until: machines.resources | length == {{ hypershift.agents_parms.agents_count }}
  retries: 30
  delay: 10
  kubernetes.core.k8s_info:
    api_version: cluster.x-k8s.io/v1beta1
    kind: Machine

- name: Create Kubeconfig for Hosted Cluster
  ansible.builtin.shell: hypershift create kubeconfig --namespace {{ hypershift.hcp.clusters_namespace }} --name {{ hypershift.hcp.hosted_cluster_name }} > /root/ansible_workdir/{{
    hypershift.hcp.hosted_cluster_name }}-kubeconfig

- name: Wait for Worker Nodes to Join
  register: nodes
  until: nodes.resources | length == {{ hypershift.agents_parms.agents_count }}
  retries: 300
  delay: 10
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    kubeconfig: /root/ansible_workdir/{{ hypershift.hcp.hosted_cluster_name }}-kubeconfig

- name: Wait for Worker nodes to be Ready
  register: node_status
  until: node_status.stdout == '0'
  retries: 50
  delay: 15
  ansible.builtin.shell: oc get no --kubeconfig=/root/ansible_workdir/{{ hypershift.hcp.hosted_cluster_name }}-kubeconfig  --no-headers | grep -i 'NotReady' | wc
    -l
