---
- name: Install Prerequisites on kvm_host
  hosts: kvm_host_hypershift
  become: true
  vars_files:
    - "{{playbook_dir}}/secrets.yaml"
  tasks:
    - name: Setting host
      ansible.builtin.set_fact:

    - name: Install Prereqs on host
      ansible.builtin.import_role:
        name: install_prerequisites_host_hypershift

- name: Create macvtap network
  hosts: kvm_host_hypershift
  become: true
  tasks:
    - name: Setting interface name
      ansible.builtin.set_fact:
        networking:

    - name: Creating macvtap network
      ansible.builtin.import_role:
        name: macvtap

- name: Create bastion for hypershift
  hosts: kvm_host_hypershift
  become: true
  vars_files:
    - "{{playbook_dir}}/secrets.yaml"
  tasks:
    - name: Creating Bastion
      when: hypershift.create_bastion == true
      ansible.builtin.include_role:
        name: create_bastion_hypershift

    - name: Setting host
      ansible.builtin.set_fact:

    - name: Install Prereqs
      ansible.builtin.import_role:
        name: install_prerequisites_host_hypershift

- name: Create macvtap network
  hosts: kvm_host_hypershift
  become: true
  tasks:
    - name: Setting interface name
      set_fact:
        networking:
          device1: "{{ hypershift.networking_device }}"
    - name: Creating macvtap network
      import_role:
        name: macvtap

- name: Create bastion for hypershift
  hosts: kvm_host_hypershift
  become: true
  vars_files:
    - "{{playbook_dir}}/secrets.yaml"
  tasks:
    - name: Creating Bastion
      include_role:
        name: create_bastion_hypershift
      when: hypershift.create_bastion == true

- name: Configuring Bastion
  hosts: bastion_hypershift
  become: true
  vars_files:
    - "{{playbook_dir}}/secrets.yaml"
  tasks:
    - name: Setting host
      set_fact:
        host: bastion_hypershift

    - name: Install Prereqs
      import_role:
        name: install_prerequisites_host_hypershift

    - name: Configure Bastion
      ansible.builtin.import_role:
        name: install_prereqs_bastion_hypershift

    - name: Add ansible SSH key to ssh-agent
      ansible.builtin.import_role:
        name: ssh_agent
