---
###################################################################################################
#  To execute this playbook you need to create a node config yaml fiile with these parameters:
# ---
# day2_compute_node:
#   vm_name: <your VM name>
#   vm_hostname: <your VM host name>
#   vm_ip: <your VM IP address>
#   hostname: <KVM host name where the VM is created>
#   host_arch: <KVM host architecture>
#
# Execute the playbook with '--extra-vars' option.
# E.g.:
# ansible-playbook playbooks/delete_compute_node.yaml --extra-vars "@extra-cnode1.yml"

- name: Delete compute node
  hosts: bastion
  gather_facts: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  pre_tasks:
    - name: Check required variables
      when: (day2_compute_node is not defined)
      block:
        - name: Check required variables
          ansible.builtin.debug:
            msg:
              - "ERROR: Variable 'day2_compute_node' is not defined!"

        - name: Abort playbook
          ansible.builtin.fail:
            msg: See above error!
